name: "Yurii Shevchuk"
url: ""
baseurl: ""
permalink: /:year/:month/:day/:title.html
markdown: kramdown
# highlighter: rouge

nav:
  - name: "About"
    href: "http://itdxer.com"

paginate: 10
paginate_path: /page:num/

# Sass
sass:
  sass_dir: _sass
  style: :compressed

google-analytics:
  id: "UA-57686913-2"

disqus:
  id: itdxer

author:
  name: Yurii Shevchuk
  github: itdxer
  linkedin: yurii-shevchuk-8434b08a
  email: mail@itdxer.com

# Scopes
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-paginate

exclude: [vendor]
